### ISSUE TITLE
password-reset uninstall failed 404 error

### ISSUE THREAD

**Issue by mbloch1986** [shinesolutions/aem-aws-stack-builder#214]
Under some circumstances the stack provisioning process may fail due to a error while uninstalling aem password reset content 1.1.0.

AEM-AWS-Stack-Builder: **3.2.1**
Packer-AEM: **3.3.0**

Error message **/var/log/shinesolutions/puppet-stack-init.log**:
```
2018-10-23 17:10:30 +1100 /Stage[main]/Aem_curator::Config_author_primary/Aem_aem[author: Wait until aem health check is ok af

ter removing all agents]/ensure (notice): ensure changed 'present' to 'aem_health_check_is_ok'

2018-10-23 17:10:31 +1100 Puppet (err): Could not set 'absent' on ensure: Unexpected response

status code: 404

headers: {"Date"=>"Tue, 23 Oct 2018 06:10:31 GMT", "Cache-Control"=>"must-revalidate,no-cache,no-store", "Content-Type"=>"text/html;charset=iso-8859-1", "Content-Length"=>"327"}

body: <html>

<head>

<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>

<title>Error 404 </title>

</head>

<body>

<h2>HTTP ERROR: 404</h2>

<p>Problem accessing /crx/packmgr/service/.json/etc/packages/shinesolutions/aem-password-reset-content-1.1.0.zip. Reason:

<pre>    Not Found</pre></p>

<hr />

</body>

</html>

(file: /opt/shinesolutions/aem-aws-stack-provisioner/modules/aem_curator/manifests/config_author_primary.pp, line: 197)

2018-10-23 17:10:31 +1100 Puppet (err): Could not set 'absent' on ensure: Unexpected response

status code: 404

headers: {"Date"=>"Tue, 23 Oct 2018 06:10:31 GMT", "Cache-Control"=>"must-revalidate,no-cache,no-store", "Content-Type"=>"text/html;charset=iso-8859-1", "Content-Length"=>"327"}

body: <html>

<head>

<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>

<title>Error 404 </title>

</head>

<body>

<h2>HTTP ERROR: 404</h2>

<p>Problem accessing /crx/packmgr/service/.json/etc/packages/shinesolutions/aem-password-reset-content-1.1.0.zip. Reason:

<pre>    Not Found</pre></p>

<hr />

</body>

</html>

(file: /opt/shinesolutions/aem-aws-stack-provisioner/modules/aem_curator/manifests/config_author_primary.pp, line: 197)

Wrapped exception:

Unexpected response

status code: 404

headers: {"Date"=>"Tue, 23 Oct 2018 06:10:31 GMT", "Cache-Control"=>"must-revalidate,no-cache,no-store", "Content-Type"=>"text/html;charset=iso-8859-1", "Content-Length"=>"327"}

body: <html>

<head>

<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
```

**Comment by mbloch1986** [comment]
Additional error messages from 

**/opt/aem/aiuthor/crx-quickstart/logs/error.log**


```
 23.10.2018 17:10:16.411 *ERROR* [OsgiInstallerImpl] com.adobe.granite.repository.impl.SlingRepositoryImpl Bundle com.shinesolutions.aem.passwordreset is NOT whitelisted to use SlingRepository.loginAdministrative

23.10.2018 17:10:16.412 *ERROR* [OsgiInstallerImpl] com.shinesolutions.aem.passwordreset.Activator Could not login to the repository
org.apache.sling.api.resource.LoginException: Bundle com.shinesolutions.aem.passwordreset is NOT whitelisted
at org.apache.sling.jcr.resource.internal.helper.jcr.JcrProviderStateFactory.getLoginException(JcrProviderStateFactory.java:203)
at org.apache.sling.jcr.resource.internal.helper.jcr.JcrProviderStateFactory.createProviderState(JcrProviderStateFactory.java:136)
at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.authenticate(JcrResourceProvider.java:304)
at org.apache.sling.jcr.resource.internal.helper.jcr.JcrResourceProvider.authenticate(JcrResourceProvider.java:76)
at org.apache.sling.resourceresolver.impl.providers.stateful.ProviderManager.authenticate(ProviderManager.java:161)
at org.apache.sling.resourceresolver.impl.providers.stateful.ProviderManager.getOrCreateProvider(ProviderManager.java:87)
at org.apache.sling.resourceresolver.impl.providers.stateful.ProviderManager.authenticateAll(ProviderManager.java:129)
at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.createControl(ResourceResolverImpl.java:138)
at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.<init>(ResourceResolverImpl.java:100)
at org.apache.sling.resourceresolver.impl.ResourceResolverImpl.<init>(ResourceResolverImpl.java:94)
at org.apache.sling.resourceresolver.impl.CommonResourceResolverFactoryImpl.getResourceResolverInternal(CommonResourceResolverFactoryImpl.java:263)
at org.apache.sling.resourceresolver.impl.CommonResourceResolverFactoryImpl.getAdministrativeResourceResolver(CommonResourceResolverFactoryImpl.java:152)
at org.apache.sling.resourceresolver.impl.ResourceResolverFactoryImpl.getAdministrativeResourceResolver(ResourceResolverFactoryImpl.java:122)
at com.shinesolutions.aem.passwordreset.Activator.start(Activator.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.felix.scr.impl.inject.methods.BaseMethod.invokeMethod(BaseMethod.java:228)
at org.apache.felix.scr.impl.inject.methods.BaseMethod.access$500(BaseMethod.java:41)
at org.apache.felix.scr.impl.inject.methods.BaseMethod$Resolved.invoke(BaseMethod.java:664)
at org.apache.felix.scr.impl.inject.methods.BaseMethod.invoke(BaseMethod.java:510)
at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:317)
at org.apache.felix.scr.impl.inject.methods.ActivateMethod.invoke(ActivateMethod.java:307)
at org.apache.felix.scr.impl.manager.SingleComponentManager.createImplementationObject(SingleComponentManager.java:334)
at org.apache.felix.scr.impl.manager.SingleComponentManager.createComponent(SingleComponentManager.java:114)
at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:947)
at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:919)
at org.apache.felix.scr.impl.manager.AbstractComponentManager.activateInternal(AbstractComponentManager.java:750)
at org.apache.felix.scr.impl.manager.AbstractComponentManager.enableInternal(AbstractComponentManager.java:661)
at org.apache.felix.scr.impl.manager.AbstractComponentManager.enable(AbstractComponentManager.java:427)
at org.apache.felix.scr.impl.manager.ConfigurableComponentHolder.enableComponents(ConfigurableComponentHolder.java:665)
at org.apache.felix.scr.impl.BundleComponentActivator.initialEnable(BundleComponentActivator.java:339)
at org.apache.felix.scr.impl.Activator.loadComponents(Activator.java:381)
at org.apache.felix.scr.impl.Activator.access$200(Activator.java:49)
at org.apache.felix.scr.impl.Activator$ScrExtension.start(Activator.java:263)
at org.apache.felix.scr.impl.AbstractExtender.createExtension(AbstractExtender.java:196)
at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:169)
at org.apache.felix.scr.impl.AbstractExtender.modifiedBundle(AbstractExtender.java:49)
at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:482)
at org.osgi.util.tracker.BundleTracker$Tracked.customizerModified(BundleTracker.java:415)
at org.osgi.util.tracker.AbstractTracked.track(AbstractTracked.java:232)
at org.osgi.util.tracker.BundleTracker$Tracked.bundleChanged(BundleTracker.java:444)
at org.apache.felix.framework.EventDispatcher.invokeBundleListenerCallback(EventDispatcher.java:915)
at org.apache.felix.framework.EventDispatcher.fireEventImmediately(EventDispatcher.java:834)
at org.apache.felix.framework.EventDispatcher.fireBundleEvent(EventDispatcher.java:516)
at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4579)
at org.apache.felix.framework.Felix.startBundle(Felix.java:2174)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:998)
at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:984)
at org.apache.sling.installer.core.impl.tasks.BundleStartTask.execute(BundleStartTask.java:97)
at org.apache.sling.installer.core.impl.OsgiInstallerImpl.doExecuteTasks(OsgiInstallerImpl.java:902)
at org.apache.sling.installer.core.impl.OsgiInstallerImpl.executeTasks(OsgiInstallerImpl.java:737)
at org.apache.sling.installer.core.impl.OsgiInstallerImpl.run(OsgiInstallerImpl.java:287)
at java.lang.Thread.run(Thread.java:748)




23.10.2018 17:11:08.986 *ERROR* [CM Event Dispatcher (Fire ConfigurationEvent: pid=org.apache.sling.jcr.resource.internal.JcrResourceResolverFactoryImpl)] com.adobe.granite.repository.impl.SlingRepositoryImpl Bundle com.shinesolutions.aem.passwordreset is NOT whitelisted to use SlingRepository.loginAdministrative
```

**Comment by mbloch1986** [comment]
Additional information:

No HTTP Request is visible in the **request.log** and **access.log**

**Comment by mbloch1986** [comment]
The problem of the 404 error is that the CRX Package Manager service  com.day.crx.packaging.impl.PackageManagerServlet is not running at the time we try to install the Package. To avoid this issue in the future we can check the response code of the URL /crx/packmgr/service/script.html. If the service is running the resonse code is 405 if not it's 404.

**Comment by mbloch1986** [comment]
Several improvement steps are included in 

* AEM-AWS-Stack-Builder 3.5.0
* AEM-AWS-Stack-Provisioner 3.5.0
* Puppet-AEM-Curator 1.9.0
