### ISSUE TITLE
NumberFormatException on Chaos Monkey component initialisation

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-aws-stack-builder#78]
The following error shows up in simianarmy log, which causes Chaos Monkey to not run.

```
2018-01-23 11:49:06.331 - ERROR MonkeyRunner - [MonkeyRunner.java:234] monkeyFactory error, cannot make monkey from com.netflix.simianarmy.basic.chaos.BasicChaosMonkey with com.netflix.simianarmy.basic.BasicChaosMonkeyContext
java.lang.NumberFormatException: For input string: ""
       at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
       at java.lang.Integer.parseInt(Integer.java:592)
       at java.lang.Integer.parseInt(Integer.java:615)
       at com.netflix.simianarmy.basic.BasicSimianArmyContext.<init>(BasicSimianArmyContext.java:147)
       at com.netflix.simianarmy.basic.BasicChaosMonkeyContext.<init>(BasicChaosMonkeyContext.java:54)
       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
       at java.lang.Class.newInstance(Class.java:442)
       at com.netflix.simianarmy.MonkeyRunner.factory(MonkeyRunner.java:229)
       at com.netflix.simianarmy.MonkeyRunner.replaceMonkey(MonkeyRunner.java:145)
       at com.netflix.simianarmy.basic.BasicMonkeyServer.addMonkeysToRun(BasicMonkeyServer.java:53)
       at com.netflix.simianarmy.basic.BasicMonkeyServer.init(BasicMonkeyServer.java:78)
       at javax.servlet.GenericServlet.init(GenericServlet.java:158)
       at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1269)
       at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1182)
       at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1072)
       at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5368)
       at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5660)
       at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
       at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
       at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
       at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
       at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
       at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
       at java.lang.Thread.run(Thread.java:748)
```

**Comment by Epoxboy** [comment]
[root@ip-10-0-15-33 ~]# cat /var/log/tomcat/localhost.2018-01-24.log 
Jan 24, 2018 11:19:17 AM org.apache.catalina.core.ApplicationContext log
SEVERE: StandardWrapper.Throwable
java.lang.NullPointerException
	at com.netflix.simianarmy.MonkeyRunner.replaceMonkey(MonkeyRunner.java:140)
	at com.netflix.simianarmy.basic.BasicMonkeyServer.addMonkeysToRun(BasicMonkeyServer.java:55)
	at com.netflix.simianarmy.basic.BasicMonkeyServer.init(BasicMonkeyServer.java:78)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1269)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1182)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1072)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5368)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5660)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Jan 24, 2018 11:19:17 AM org.apache.catalina.core.StandardContext loadOnStartup
SEVERE: Servlet [Monkey Server] in web application [/simianarmy] threw load() exception
java.lang.NullPointerException
	at com.netflix.simianarmy.MonkeyRunner.replaceMonkey(MonkeyRunner.java:140)
	at com.netflix.simianarmy.basic.BasicMonkeyServer.addMonkeysToRun(BasicMonkeyServer.java:55)
	at com.netflix.simianarmy.basic.BasicMonkeyServer.init(BasicMonkeyServer.java:78)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1269)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1182)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1072)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5368)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5660)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1260)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2002)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Epoxboy** [comment]
java.lang.NullPointerException error implies some input error in MonkeyRunner.java line 140 or 139, which is related to monkeyClass ?

**Comment by Epoxboy** [comment]
I've found the problem is from client.properties file, the following two items are causing the error:
simianarmy.client.aws.proxyHost =
simianarmy.client.aws.proxyPort =

and if you # them, the above monkeyRunner error will be gone and Monkeys can start normally, you can see the simple DB domain created accordingly too. here are the proper logs from simianarmy.log

2018-02-01 16:14:21.333 - INFO  MonkeyRunner - [MonkeyRunner.java:56] Starting CHAOS Monkey
2018-02-01 16:14:21.658 - INFO  MonkeyRunner - [MonkeyRunner.java:56] Starting VOLUME_TAGGING Monkey
2018-02-01 16:14:21.663 - INFO  Monkey - [Monkey.java:142] Not Time for CHAOS Monkey
2018-02-01 16:14:21.708 - INFO  MonkeyRunner - [MonkeyRunner.java:56] Starting JANITOR Monkey
2018-02-01 16:14:21.715 - INFO  Monkey - [Monkey.java:142] Not Time for VOLUME_TAGGING Monkey
2018-02-01 16:14:21.750 - INFO  MonkeyRunner - [MonkeyRunner.java:56] Starting CONFORMITY Monkey
2018-02-01 16:14:21.758 - INFO  Monkey - [Monkey.java:142] Not Time for JANITOR Monkey
2018-02-01 16:14:21.837 - INFO  Monkey - [Monkey.java:142] Not Time for CONFORMITY Monkey

**Comment by Epoxboy** [comment]
added empty string check to client_properties.erb in puppet-simianarmy module. related issue #3 .
